
 import { Inter } from 'next/font/google'
import './globals.css'
import './index.css'
import TodoProvider from './Context/TodoContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <TodoProvider>

        {children}
        </TodoProvider>
     
        </body>
    </html>
  )
}
